# Generated by Django 3.0.7 on 2022-04-02 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0030_auto_20220402_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 11, 37, 56, 135827)),
        ),
    ]
